source_url : https://xkcd.com
db_file : "database/database.json"
parallel : 7 

# Количество логических ядер на моём ноутбуке равно 8. 
# Сделала -1 на всякий случай, чтобы одно ядро было свободно для других задач.